### ISSUE TITLE
Error when adding a CKAN harvest source

### ISSUE THREAD

**Issue by smihai** [etalab/udata#343]
The following traceback occurs when adding CKAN harvest source:
```
Traceback (most recent call last):
  File "/srv/udata/local/lib/python2.7/site-packages/udata/harvest/backends/base.py", line 121, in process_item
    dataset = self.process(item)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/harvest/backends/ckan.py", line 146, in process
    data = self.validate(response['result'], schema)
  File "/srv/udata/local/lib/python2.7/site-packages/udata/harvest/backends/base.py", line 218, in validate
    raise HarvestException(msg)
HarvestException: Validation error:
- [resources.0.filesize] required key not provided: None

```
CKAN API exposes the resource filesize in _size_ attribute, and not _filesize_, as seen for example on http://demo.ckan.org/api/3/action/package_show?id=adur_district_spending

**Comment by noirbizarre** [comment]
Thanks for reporting.
I'll look into this as soon as possible !

**Comment by noirbizarre** [comment]
It seams to have change but I can't find when or why.
Here the sample responses used in tests: https://github.com/etalab/udata/blob/master/udata/harvest/tests/ckan-dataset-2.json
Here the same response now: http://demo.ckan.org/api/3/action/package_show?id=afterfibre

You will notice the filesize has become size.
